---
AWSTemplateFormatVersion: 2010-09-09
Description: Affix RDS template
Parameters:
  VpcStackName:
    Type: String
    Default: affix-vpc
  SecurityGroupStackName:
    Type: String
    Default: affix-security-groups
Resources:
  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.small
      Engine: sqlserver-ex
      EngineVersion: "15.00.4236.7.v1"
      LicenseModel: "license-included"
      MasterUsername: affixsa
      MasterUserPassword: 19873jhe02*
      AllocatedStorage: "20"
      PubliclyAccessible: true
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${SecurityGroupStackName}-DbSecurityGroup
      DBSubnetGroupName: !Ref AffixDbSubnetGroup
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 23:00-23:30
      PreferredMaintenanceWindow: sun:03:00-sun:04:00
  AffixDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: AffixDb subnet group
      DBSubnetGroupName: AffixDbSubnets
      SubnetIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetAZ1
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetAZ2

Outputs:
  MyDBInstanceEndpoint:
    Description: Endpoint for the created RDS database
    Value: !Sub ${Instance.Endpoint.Address}:${Instance.Endpoint.Port}
    Export:
      Name: !Sub ${AWS::StackName}-db-endpoint

