---
AWSTemplateFormatVersion: 2010-09-09
Description: RDS db template
Parameters:
  VpcStackName:
    Type: String
    Default: affix-vpc
  SecurityGroupStackName:
    Type: String
    Default: affix-security-groups
Resources:
  AffixDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      DBName: affix-db
      Engine: sqlserver-ex
      EngineVersion: "15.00.4236.7.v1"
      LicenseModel: "license-included"
      MasterUsername: affix-sa
      MasterUserPassword: 19873jhe02*
      AllocatedStorage: "20"
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Sub ${SecurityGroupStackName}-DbSecurityGroup
      DBSubnetGroupName: !Sub ${VpcStackName}-PublicSubnetAZ1
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 23:00-23:30
      PreferredMaintenanceWindow: sun:03:00-sun:04:00
Outputs:
  MyDBInstanceEndpoint:
    Description: Endpoint for the created RDS database
    Value: !Sub ${AffixDb.Endpoint.Address}:${AffixDb.Endpoint.Port}
