---
AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster Template
Parameters:
  VpcStackName:
    Type: String
    Default: affix-vpc
  SecurityGroupStackName:
    Type: String
    Default: affix-security-groups

Resources:  
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub ${VpcStackName}-PublicSubnetAZ1
        - Fn::ImportValue: !Sub ${VpcStackName}-PublicSubnetAZ2
      SecurityGroups:
        - Fn::ImportValue: !Sub ${SecurityGroupStackName}-LoadBalancerSecurityGroup
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      #        - Key: access_logs.s3.enabled
      #          Value: true
      #        - Key: access_logs.s3.bucket
      #          Value: affix-load-balancer-logs
      IpAddressType: ipv4
  
  # TODO Enable ALBListener HTTPS forwarding once you have a valid certificate
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBDefaultTargetGroup
      Port: 80
      Protocol: HTTP
      #SslPolicy: ELBSecurityPolicy-2016-08 # Default security policy.
      # More info here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
  #      Certificates:
  #        - CertificateArn: !Ref ECSClusterCertificate
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/html
            MessageBody: |
              <!DOCTYPE html>
              <html>
                <head>
                  <title>Page unrecognized</title>
                </head>
                <body>
                    <div>404</div>
                </body>
              </html>
            StatusCode: 404
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "*"
      ListenerArn: !Ref ALBListener
      Priority: 50000

  ALBDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ECSClusterTargetGroup
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VPC
      TargetType: instance
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      

Outputs:
  ALB:
    Description: The application load balancer
    Value: !Ref ALB
    Export:
      Name: !Sub ${AWS::StackName}-ALB
  ALBListenerARN:
    Value: !Ref ALBListener
    Export:
      Name: !Sub ${AWS::StackName}-ALBListenerARN
  ALBDefaultTargetGroup:
    Value: !Ref ALBListener
    Export:
      Name: !Sub ${AWS::StackName}-ALBDefaultTargetGroup