---
AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster
Parameters:
  VpcStackName:
    Type: String
    Default: affix-vpc

Resources:
  ECSHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VPC
      # TODO: Restrict port access to ports 22 (SSH and ports used by the ALB). You can use the SourceSecurityGroupId property and provide it the ALB security group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      # TODO: same restrictions as above
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Provides access to the load balancer that sits in front of ECS
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 5005
          ToPort: 5005
      SecurityGroupEgress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: -1

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for affix DB access
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0

  JumpHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for affix jump host(s)
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

Outputs:
  ECSHostSecurityGroup:
    Description: A reference to the security group for ECS hosts
    Value: !Ref ECSHostSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ECSHostSecurityGroup

  LoadBalancerSecurityGroup:
    Description: A reference to the security group for load balancers
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-LoadBalancerSecurityGroup
  DbSecurityGroup:
    Description: A reference to the security group for the db instance
    Value: !Ref DbSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-DbSecurityGroup