# Used for local development

version: '3.9'

services:
    reverseproxy:
      build:
        context: .
        dockerfile: Affix.ReverseProxy/nginx.Dockerfile
      depends_on:
        - identityserver
      ports:
        - "443:443" # container port must match the port that nginx is listening on
      networks:
        affixnet:
          aliases:
            - "local.is.affix.com"
            - "local.api.affix.com"

    db:
      build:
        context: .
        dockerfile: Affix.DB/db.Dockerfile
      restart: always
      ports:
        - "1430:1433"
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssword1
      networks:
        - affixnet

    identityserver:
      build:
        context: .
        dockerfile: Affix.IdentityServer/Dockerfile
      ports:
        - "5000:5000"
      environment:
        - ASPNETCORE_URLS=http://*:5000
        - ASPNETCORE_ENVIRONMENT=Local
      networks:
        - affixnet
   
    api:
      build:
        context: .
        dockerfile: Affix.API/Dockerfile
      ports:
        - "5005:5005"
      environment:
        - ASPNETCORE_URLS=http://*:5005
        - ASPNETCORE_ENVIRONMENT=Local
      networks:
        - affixnet

    client:
      build:
        context: .
        dockerfile: Affix.Client/Dockerfile
      ports:
        - "5555:5555"
      environment:
        - ASPNETCORE_URLS=http://*:5555
        - ASPNETCORE_ENVIRONMENT=Development
      networks:
        - affixnet

networks:
  affixnet: {}