version: '3.9'

services:
    reverseproxy:
      build:
        context: .
        dockerfile: Affix.ReverseProxy/nginx.Dockerfile
      depends_on:
        - identityserver
      ports:
        - "443:443" # container port must match the port that nginx is listening on
      networks:
        affixnet:
          aliases:
            - "local.is.affix.com"
            - "local.api.affix.com"

    identityserver:
      build:
        context: .
        dockerfile: Affix.IdentityServer/Dockerfile
      ports:
        - "5000:5000"
      environment:
        - ASPNETCORE_URLS=http://*:5000
        - ASPNETCORE_ENVIRONMENT=Local
      networks:
        - affixnet
   
    api:
      build:
        context: .
        dockerfile: Api/Dockerfile
      ports:
        - "5005:5005"
      environment:
        - ASPNETCORE_URLS=http://*:5005
        - ASPNETCORE_ENVIRONMENT=Local
      networks:
        - affixnet

networks:
  affixnet: {}