# Use a multi-stage build to reduce the size of the final image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Copy the project file and restore dependencies first, to take advantage of Docker's caching
WORKDIR /src
COPY ["Affix.API/Affix.API.csproj", "Affix.API/"]
RUN dotnet restore "Affix.API/Affix.API.csproj"

# Copy the rest of the source code and build the project
COPY . .
WORKDIR "/src/Affix.API"
RUN dotnet build "Affix.API.csproj" -c Local -o /app/build

# Publish the project
RUN dotnet publish "Affix.API.csproj" -c Local -o /app/publish

# Use a smaller base image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app

# Copy the published app and the certificate file
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Affix.API.dll"]
