name: Affix

on:
  push:
    branches: [ master ]
    paths:
      - 'Api/**'
      - 'Client/**'
  # pull_request:
  #   branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.200
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWSREGION }}
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
    - name: Install dotnet-eb tool
      run: dotnet tool install -g amazon.elasticbeanstalk.tools
    - name: Deploy to Elastic Beanstalk
      run: ${{ secrets.DEPLOYCOMMAND }}
